### ISSUE TITLE
ggplot object unusable on second call with facet_wrap_paginate

### ISSUE THREAD

**Issue by guiastrennec** [thomasp85/ggforce#70] opened 2017-04-11 17:06 UTC
Nice work with `facet_wrap_paginate()`, however I am unexpected results with the following script.

```r
library(ggforce)

# A plot with facet_wrap_paginate
p <- ggplot(diamonds, aes(x = carat, y = price)) +
  geom_point() +
  facet_wrap_paginate(facets = 'color', ncol = 2, nrow = 2, page = 1)

# Renders plot properly
print(p)

# On all subsequent call an error is returned
print(p)
Error in `$<-.data.frame`(`*tmp*`, "page", value = numeric(0)) : replacement has 0 rows, data has 7

Is is possible to prevent this behavior?

**Comment by guiastrennec** [comment] 2017-09-21 01:33
Any updates regarding this issue? or maybe a workaround for use inside functions? I tried the following but it was unsuccessful.
```
temp <- p
print(p)
p <- temp
print(p)
```

I am assuming it has something to do with environments in `p$facet` but I could not figure it out.

**Comment by thomasp85** [comment] 2017-09-21 07:20
I have not had time to look into it yet - I’ll do a bug sweep before next release

**Comment by guiastrennec** [comment] 2017-09-21 08:55
Thanks for the prompt answer!

**Comment by guiastrennec** [comment] 2017-09-21 13:03
If it can be of any help, I found what could be a cause and a small workaround.

It seems that after calling `print(p)` the `p$facet$params` is modified and losses the `p$facet$params$nrow` value (note that on the other hand it gains `p$facet$params$max_rows`). Hence the following example can be used "repair" a plot object (`p`):

```
p$facet$params$nrow <- 2  # Restores the nrow parameter to its previous value
print(p)                  # Now works again
```

However this fix has to be done for each plot call.

**Comment by thomasp85** [comment] 2017-09-21 13:16
Thanks for looking into it - will def help with the fix👍

**Comment by thomasp85** [comment] 2019-02-28 14:01
I cannot reproduce the original issue with current versions. I'm closing but feel free to reopen with a reprex if it persists

**Closed by thomasp85** 2019-02-28 14:01 UTC
