### ISSUE TITLE
R > 3.3.0 constraint

### ISSUE THREAD

**Issue by gasseam1** [thomasp85/ggforce#68] opened 2017-03-31 08:48 UTC
Hi,

Fisrt thank you for this excellent package. Is it  any reason to use a recent version of  R?Why  do you need R>3.3.0?

**Comment by thomasp85** [comment] 2017-04-27 13:34
Duplicate of #55 – this will hopefully change in the future

**Closed by thomasp85** 2017-04-27 13:34 UTC
